services:
    sitemap_dumper:
        class:      KPhoen\SitemapBundle\Dumper\GzFileDumper
        arguments:  [ %kernel.root_dir%/../web/sitemap.xml.gz ]

    sitemap_formatter:
        class:      KPhoen\SitemapBundle\Formatter\XmlFormatter

    sitemap:
        class:      KPhoen\SitemapBundle\Sitemap\Sitemap
        arguments:  [ @sitemap_dumper, @sitemap_formatter, %sitemap.config.base_host% ]
